# Generated by Django 6.0.1 on 2026-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_remove_dosen_created_at_dosen_award_dosen_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='penelitian',
            field=models.TextField(default=True, null=True),
        ),
    ]
