# Generated by Django 6.0.2 on 2026-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_alter_dosen_penelitian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='penelitian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
