# Generated by Django 6.0.2 on 2026-02-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(max_length=10, unique=True)),
                ('nama_fakultas', models.CharField(max_length=100)),
                ('nama_dekan', models.CharField(max_length=100)),
                ('gedung', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
