# Generated by Django 6.0.2 on 2026-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0002_alter_fakultas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
