# Generated by Django 6.0.1 on 2026-02-04 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_studi', '0002_alter_programstudi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id_mk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_mk', models.CharField(max_length=10, unique=True)),
                ('nama_mk', models.CharField(max_length=100)),
                ('sks', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('jenis_mk', models.CharField(choices=[('Wajib', 'Wajib'), ('Pilihan', 'Pilihan'), ('Praktikum', 'Praktikum')], max_length=20)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to='program_studi.programstudi')),
            ],
        ),
    ]
