# Generated by Django 6.0.2 on 2026-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='bahan_kajian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='cpm',
            field=models.TextField(blank=True, null=True, verbose_name='Capaian Pembelajaran Mata Kuliah (CPM)'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='cpps',
            field=models.TextField(blank=True, null=True, verbose_name='Capaian Pembelajaran Program Studi (CPPS)'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='daftar_rujukan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='instrumen_penilaian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
