# Generated by Django 6.0.2 on 2026-02-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah', '0002_matakuliah_bahan_kajian_matakuliah_cpm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliah',
            name='id_mk',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='cpm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='cpps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
