# Generated by Django 6.0.1 on 2026-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah', '0003_remove_matakuliah_id_mk_matakuliah_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='jenis_mk',
            field=models.CharField(choices=[('wajib', 'Wajib'), ('pilihan', 'Pilihan'), ('praktikum', 'Praktikum')], max_length=20),
        ),
    ]
