# Generated by Django 5.2.11 on 2026-02-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fakultas', '0002_alter_fakultas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10, unique=True)),
                ('nama_prodi', models.CharField(max_length=100)),
                ('jenjang', models.CharField(choices=[('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=2)),
                ('akreditasi', models.CharField(max_length=1)),
                ('kaprodi', models.CharField(max_length=100)),
                ('id_fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='fakultas.fakultas')),
            ],
        ),
    ]
