# Generated by Django 6.0.1 on 2026-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_studi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
