# Generated by Django 6.0.2 on 2026-02-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dosen',
        ),
    ]
