# Generated by Django 6.0.1 on 2026-01-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=150)),
                ('nidn', models.CharField(max_length=20)),
                ('fakultas', models.CharField(max_length=100)),
                ('program_studi', models.CharField(max_length=100)),
                ('penelitian', models.BooleanField(default=False)),
                ('foto_dosen', models.ImageField(upload_to='dosen/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
