# Generated by Django 6.0.1 on 2026-02-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_category_tag_article_category_article_tags'),
        ('article', '0003_dosen'),
    ]

    operations = [
    ]
