# Generated by Django 5.2.11 on 2026-02-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_id_alter_articleimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='award',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='mata_kuliah_diampu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='orchid_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pendidikan_s1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pendidikan_s2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pendidikan_s3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pengabdian_masyarakat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='publikasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='research_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='researcher_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='scopus_author_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='foto_dosen',
            field=models.ImageField(blank=True, null=True, upload_to='dosen/'),
        ),
    ]
