# Generated by Django 6.0.2 on 2026-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_merge_20260201_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='penelitian',
            field=models.TextField(max_length=255),
        ),
    ]
