# Generated by Django 6.0.1 on 2026-02-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_id_alter_articleimage_id_and_more'),
        ('article', '0005_alter_dosen_penelitian'),
    ]

    operations = [
    ]
