# Generated by Django 6.0.1 on 2026-02-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_merge_20260130_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='penelitian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
